id: P006617
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 12:10:35.349532
source_metadata:
  id: bdr:W1KG8824
  title: གྲུབ་དབང་ཤཱཀྱ་ཤྲཱིའི་རྣམ་ཐར་མེ་ཏོག་ཕྲེང་བ།
  author: ''
  volumes:
    dbcf3900dae54553b88d7281aff6719f:
      image_group_id: I1KG8826
      title: ''
      volume_number: 1
      total_pages: 216
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
